export const S = {
  LOADING: "⧗",
  REFRESH: "⟳",
  SUCCESS: "✓",
  FAIL: "×",
  WARN: "⚠",
  STOP: "∎",
  BULLET: "›",
  BULLET_ALT: "•",
  LIST: "»",
  SEPARATOR: "━",
  SEPARATOR_LIGHT: "─",
  PIPE: "│",
  ARROW_R: "→",
  ARROW_UP: "↑",
  ARROW_DOWN: "↓",
  DOT: "·",
  STAR: "★",
  DIAMOND: "◇",
  DIAMOND_FILL: "◆",
  CIRCLE: "●",
  RING: "○",
  SQUARE: "■",
  DASH: "—",
  ELLIPSIS: "…",

  SUN: "☀",
  CLOUD: "☁",
  RAIN: "☂",
  UMBRELLA: "☔",
  SNOW: "❄",
  STORM: "⚡",
  WIND: "≋",
  TEMP: "°",
  TEMP_HIGH: "⋀",
  TEMP_LOW: "⋁",

  NOTE: "♪",
  NOTES: "♫",
  PLAY: "▶",
  PAUSE: "⏸",
  DISC: "◎",
  FLOWER: "⚘",

  UP: "▲",
  DOWN: "▼",
  CHART: "↝",
  CURRENCY: "◈",
  WALLET: "☖",
  PERCENT: "%",

  PALETTE: "◈",
  LENS: "◎",
  BULB: "⁂",
  GLOBE: "⊕",
  PIN: "⊙",
  SCROLL: "⌘",
  PERSON: "⌂",
  MOSQUE: "☽",
  FILM: "▣",
  BOOK: "§",
  CLOCK: "⏱",
  LINK: "⟁",
  SHIELD: "⛊",
  DICE: "⚄",
  SPARK: "∗",

  BORDER_TL: "⎡",
  BORDER_TR: "⎤",
  BORDER_BL: "⎣",
  BORDER_BR: "⎦",
  GRADIENT: "░▒▓",
} as const;

export type SymbolKey = keyof typeof S;

export function separator(length: number = 20): string {
  return S.SEPARATOR.repeat(length);
}
